language: python
python:
  - "3.6"
  - "3.7"

install:
  - pip install -r ./requirements.txt

script:
  - python testDevTool.py
  - python testNewProject.py

notifications:
  on_success: always
cache: pip