Test:   # function name
  doc : Test function of this script
  parameters:
    - a : param a
      b : param b
      c : param c
  definitions:
    a :
      type : str
      default : ggg
    b :
      type : int
      default : 20
    c :
      type : list
      default : []
  others:
    a :
      pa : pa
      ppa : ppa
    b :
      - pb
      - ppb
    c :
      - pc
        ppc 
    d :
      e :
        f :
          h : this is H
        